//! v2 membership — the **invite-chain credential system** (docs/MESH_V2.md §3).
//!
//! Genesis creates a **master keypair**. A joiner generates its **own** keypair and
//! is admitted by a **cert** that an inviter signs, binding `(member pubkey,
//! in-mesh id, name, inviter)`. The inviter is the master, or — in an `OpenChain`
//! mesh — any already-valid member. Certs chain back to the master: a member is
//! valid iff its cert chains to the master.
//!
//! Crucially, **verification needs only public keys + signatures** — the master
//! private key is NEVER required to verify (§3), so it can stay on the creator's
//! node alone. Day-to-day auth and the cert-gossip roster (docs/MESH_V2.md §10)
//! build on this.

use std::collections::HashSet;

use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};

use crate::charter::InviteTopology;
use lattice_proto::wire_v2::MemberId;

/// A 32-byte ed25519 public key (the master's, or a member's, identity).
pub type PubKey = [u8; 32];

/// The master signing key — the mesh's root of trust. Lives ONLY on the creator's
/// node (or split via threshold; out of scope here).
pub struct MasterKey(SigningKey);

/// A member's own signing key — generated by the member; the private half never
/// leaves the device.
pub struct MemberKey(SigningKey);

/// A signed membership credential binding a member to the mesh.
#[derive(Clone, PartialEq, Eq, Debug, Serialize, Deserialize)]
pub struct Cert {
    /// The mesh identity = the master public key.
    pub network: PubKey,
    /// This member's public key.
    pub member: PubKey,
    /// 1-byte in-mesh id (join order).
    pub id: MemberId,
    /// The name chosen at join.
    pub name: String,
    /// The pubkey that signed this cert: the master, or an inviting member.
    pub inviter: PubKey,
    pub issued_at: u64,
    /// `inviter`'s signature over the canonical bytes.
    #[serde(with = "sig_serde")]
    pub sig: [u8; 64],
}

/// serde's built-in array impls stop at length 32, so route the 64-byte signature
/// through a byte sequence. Shared by the membership and discovery records.
pub(crate) mod sig_serde {
    use serde::{Deserialize, Deserializer, Serialize, Serializer};
    pub fn serialize<S: Serializer>(v: &[u8; 64], s: S) -> Result<S::Ok, S::Error> {
        v.as_slice().serialize(s)
    }
    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<[u8; 64], D::Error> {
        let v = Vec::<u8>::deserialize(d)?;
        v.try_into()
            .map_err(|_| serde::de::Error::custom("signature must be 64 bytes"))
    }
}

/// Canonical bytes a cert is signed over (length-prefixed name so it can't be
/// confused with adjacent fields).
fn signing_bytes(
    network: &PubKey,
    member: &PubKey,
    id: MemberId,
    name: &str,
    inviter: &PubKey,
    issued_at: u64,
) -> Vec<u8> {
    let mut b = Vec::with_capacity(32 + 32 + 1 + 2 + name.len() + 32 + 8);
    b.extend_from_slice(network);
    b.extend_from_slice(member);
    b.push(id);
    b.extend_from_slice(&(name.len() as u16).to_be_bytes());
    b.extend_from_slice(name.as_bytes());
    b.extend_from_slice(inviter);
    b.extend_from_slice(&issued_at.to_be_bytes());
    b
}

impl MasterKey {
    pub fn generate() -> Self {
        Self(SigningKey::generate(&mut rand::rngs::OsRng))
    }
    /// Restore from the 32-byte secret seed (creator-held; never shared).
    pub fn from_seed(seed: &[u8; 32]) -> Self {
        Self(SigningKey::from_bytes(seed))
    }
    pub fn to_seed(&self) -> [u8; 32] {
        self.0.to_bytes()
    }
    /// The mesh's network id (= master public key).
    pub fn network(&self) -> PubKey {
        self.0.verifying_key().to_bytes()
    }
    /// Issue a master-signed cert for `member` (inviter = master).
    pub fn issue(&self, member: PubKey, id: MemberId, name: &str, issued_at: u64) -> Cert {
        let network = self.network();
        let msg = signing_bytes(&network, &member, id, name, &network, issued_at);
        Cert {
            network,
            member,
            id,
            name: name.into(),
            inviter: network,
            issued_at,
            sig: self.0.sign(&msg).to_bytes(),
        }
    }
}

impl MemberKey {
    pub fn generate() -> Self {
        Self(SigningKey::generate(&mut rand::rngs::OsRng))
    }
    pub fn from_seed(seed: &[u8; 32]) -> Self {
        Self(SigningKey::from_bytes(seed))
    }
    pub fn pubkey(&self) -> PubKey {
        self.0.verifying_key().to_bytes()
    }
    /// Sign arbitrary bytes with this member's key (used by discovery records).
    pub(crate) fn sign(&self, msg: &[u8]) -> [u8; 64] {
        self.0.sign(msg).to_bytes()
    }
    /// Invite a new member (open-chain): this member signs the child cert.
    pub fn invite(
        &self,
        network: PubKey,
        member: PubKey,
        id: MemberId,
        name: &str,
        issued_at: u64,
    ) -> Cert {
        let inviter = self.pubkey();
        let msg = signing_bytes(&network, &member, id, name, &inviter, issued_at);
        Cert {
            network,
            member,
            id,
            name: name.into(),
            inviter,
            issued_at,
            sig: self.0.sign(&msg).to_bytes(),
        }
    }
}

impl Cert {
    /// Does the signature verify against the inviter's key? (Self-consistency only —
    /// chaining to the master is checked by [`valid_members`].)
    pub fn sig_ok(&self) -> bool {
        let Ok(vk) = VerifyingKey::from_bytes(&self.inviter) else {
            return false;
        };
        let sig = Signature::from_bytes(&self.sig);
        let msg = signing_bytes(
            &self.network,
            &self.member,
            self.id,
            &self.name,
            &self.inviter,
            self.issued_at,
        );
        vk.verify(&msg, &sig).is_ok()
    }
}

/// From a bag of gossiped `certs`, return those that **validly chain to the
/// master** under the mesh's invite `topology`. This is the admin-free roster:
/// each cert is self-proving, so no quorum or directory signature is needed
/// (docs/MESH_V2.md §10).
pub fn valid_members<'a>(
    master: &PubKey,
    certs: &'a [Cert],
    topology: InviteTopology,
) -> Vec<&'a Cert> {
    // Keep only self-consistent certs for THIS network.
    let ok: Vec<&Cert> = certs
        .iter()
        .filter(|c| &c.network == master && c.sig_ok())
        .collect();
    // Fixpoint: a member is rooted if its inviter is the master, or (open chain) a
    // member already known to be rooted.
    let mut rooted: HashSet<PubKey> = HashSet::new();
    let mut changed = true;
    while changed {
        changed = false;
        for c in &ok {
            if rooted.contains(&c.member) {
                continue;
            }
            let authorized = &c.inviter == master
                || (topology == InviteTopology::OpenChain && rooted.contains(&c.inviter));
            if authorized {
                rooted.insert(c.member);
                changed = true;
            }
        }
    }
    ok.into_iter().filter(|c| rooted.contains(&c.member)).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn at() -> u64 {
        1_700_000_000
    }

    #[test]
    fn master_issued_cert_is_valid_and_verifies() {
        let master = MasterKey::from_seed(&[1u8; 32]);
        let alice = MemberKey::from_seed(&[2u8; 32]);
        let cert = master.issue(alice.pubkey(), 1, "alice", at());
        assert!(cert.sig_ok());
        let valid = valid_members(&master.network(), std::slice::from_ref(&cert), InviteTopology::OpenChain);
        assert_eq!(valid.len(), 1);
        assert_eq!(valid[0].member, alice.pubkey());
    }

    #[test]
    fn open_chain_member_invite_chains_to_master() {
        let master = MasterKey::from_seed(&[1u8; 32]);
        let net = master.network();
        let alice = MemberKey::from_seed(&[2u8; 32]);
        let bob = MemberKey::from_seed(&[3u8; 32]);
        // master admits alice; alice invites bob.
        let c_alice = master.issue(alice.pubkey(), 1, "alice", at());
        let c_bob = alice.invite(net, bob.pubkey(), 2, "bob", at());
        let certs = vec![c_alice, c_bob];
        let valid = valid_members(&net, &certs, InviteTopology::OpenChain);
        let members: HashSet<PubKey> = valid.iter().map(|c| c.member).collect();
        assert!(members.contains(&alice.pubkey()));
        assert!(members.contains(&bob.pubkey()));
    }

    #[test]
    fn master_gated_rejects_member_invites() {
        let master = MasterKey::from_seed(&[1u8; 32]);
        let net = master.network();
        let alice = MemberKey::from_seed(&[2u8; 32]);
        let bob = MemberKey::from_seed(&[3u8; 32]);
        let c_alice = master.issue(alice.pubkey(), 1, "alice", at());
        let c_bob = alice.invite(net, bob.pubkey(), 2, "bob", at()); // alice is not the master
        let certs = vec![c_alice, c_bob];
        let valid = valid_members(&net, &certs, InviteTopology::MasterGated);
        let members: HashSet<PubKey> = valid.iter().map(|c| c.member).collect();
        assert!(members.contains(&alice.pubkey()));
        assert!(!members.contains(&bob.pubkey())); // member-invite not authorized
    }

    #[test]
    fn tampered_cert_fails() {
        let master = MasterKey::from_seed(&[1u8; 32]);
        let alice = MemberKey::from_seed(&[2u8; 32]);
        let mut cert = master.issue(alice.pubkey(), 1, "alice", at());
        cert.name = "mallory".into(); // signature no longer matches
        assert!(!cert.sig_ok());
        assert!(valid_members(&master.network(), std::slice::from_ref(&cert), InviteTopology::OpenChain).is_empty());
    }

    #[test]
    fn cert_for_another_network_is_ignored() {
        let master = MasterKey::from_seed(&[1u8; 32]);
        let other = MasterKey::from_seed(&[9u8; 32]);
        let alice = MemberKey::from_seed(&[2u8; 32]);
        // a cert validly signed by `other`, but we verify against `master`'s network.
        let foreign = other.issue(alice.pubkey(), 1, "alice", at());
        assert!(foreign.sig_ok());
        assert!(valid_members(&master.network(), std::slice::from_ref(&foreign), InviteTopology::OpenChain).is_empty());
    }
}
